#pragma once

#include <functional>
#include <map>
#include <mutex>
#include <queue>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

// ─── Data structures ──────────────────────────────────────────────────────────

struct Order {
    std::string id;
    std::string user_id;
    std::string symbol;

    enum class Type { LIMIT, MARKET } type;
    enum class Side { BUY, SELL } side;
    enum class Status { OPEN, PARTIAL, FILLED, CANCELLED } status = Status::OPEN;

    double price    = 0.0;
    double quantity = 0.0;
    double filled_qty = 0.0;
    long long timestamp = 0;
};

struct Trade {
    std::string trade_id;
    std::string symbol;
    double price;
    double quantity;
    std::string buy_order_id;
    std::string sell_order_id;
    std::string buyer_id;
    std::string seller_id;
    long long timestamp;
};

// Bids: descending price (highest bid first)
using BidBook = std::map<double, std::queue<Order>, std::greater<double>>;
// Asks: ascending price (lowest ask first)
using AskBook = std::map<double, std::queue<Order>>;

// ─── OrderBook ────────────────────────────────────────────────────────────────

class OrderBook {
public:
    explicit OrderBook(const std::string& symbol);

    // Returns list of trades generated by this order (may be empty for resting limit orders)
    std::vector<Trade> place_order(Order order);

    // Returns true if order was found and cancelled
    bool cancel_order(const std::string& order_id);

    // Snapshot for Redis cache: top `depth` levels on each side
    // Returns {bids, asks} where each entry is {price, total_qty_at_level}
    std::pair<std::vector<std::pair<double, double>>,
              std::vector<std::pair<double, double>>>
    snapshot(int depth = 20) const;

private:
    std::string symbol_;
    BidBook bids_;
    AskBook asks_;

    // Fast lookup for cancel: order_id → {side_string, price}
    struct OrderRef {
        std::string side;  // "buy" or "sell"
        double price;
    };
    std::unordered_map<std::string, OrderRef> order_index_;

    mutable std::mutex mtx_;

    std::vector<Trade> match_limit_order(Order& aggressor);
    std::vector<Trade> match_market_order(Order& aggressor);

    Trade make_trade(Order& resting, Order& aggressor,
                     double exec_price, double exec_qty);

    // Remove empty price levels after matching
    void prune_empty_levels();
};
